### ISSUE TITLE
seifjava

### ISSUE THREAD

**Issue by 4thex** [paypal/seifnode#27]
I am coming up for air after almost a year of working on a side-project. I was wondering if it would be an idea to create a seifjava project. It seems to me that as these seif services start emerging, existing Java services would need an easy way to connect to them.
If you think it is a good idea, I could start a side-project to this one, but under the seif branding.

**Comment by aashish-sheshadri** [comment]
@4thex That sounds awesome!! Seif crypto services for Java is on our roadmap, we would definitely appreciate your contribution. 

We will be happy to work with you on this -- basically we need ECC-521, modified link encryption using AES-256, SHA3-256 and ISAAC RNG in java (http://burtleburtle.net/bob/rand/isaacafa.html).

Let us know if you have questions, if this thread can't contain it we can open a slack channel.

**Comment by 4thex** [comment]
Bob Jenkins already created a Java implementation of ISAAC and published it here:
http://burtleburtle.net/bob/java/rand/Rand.java
I need to read up on what exactly ECC-521 is.

**Comment by aashish-sheshadri** [comment]
You'd not want to implement any of the crypto protocols, but rather use a well known crypto library which offers ECC-521 public key encryption and AES-256 symmetric encryption. Currently for node we use Cryptopp library.

**Comment by 4thex** [comment]
OK. That makes sense. I have researched different existing crypto implementations for Java, and my choice has fallen on bouncycastle.org. They have the implementations I need 

- ISAAC: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/engines/ISAACEngine.java
- AES: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/engines/AESEngine.java
- SHA3: https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/digests/SHA3Digest.java

The license is MIT, so there should be no problem with using this library also in commercial implementations.
If you approve, I will move forward with that choice.

Can you create a repository for seifjava. I can then send pull requests there.

**Comment by mreinstein** [comment]
I guess what I don't understand is, can't we just get java bindings to the official seifnode stuff? Is it really necessary/a good idea to build a parallel implementation?

**Comment by 4thex** [comment]
I am not aware of a way to run NodeJS code from Java directly. You would need to spawn a NodeJS process and communicate with it. This would have a significant performance impact.
Another opportunity is to use JNI to access the same C++ dependencies that the NodeJS project uses, but there is also a performance penalty to pay here.
I am not sure what you mean with Java bindings to NodeJS. Can you point me to the specific technology you are referring to?

**Comment by 4thex** [comment]
When I calculate the hash for "abc" using BC, I get this result:
3A985DA74FE225B2045C172D6BD390BD855F086E3E9D525B46BFE24511431532

It is not the same as the test here: [https://github.com/paypal/seifnode/blob/master/test/shatest.js]

I am not sure where the difference is. I can check in the code if you'd like.

The code I am using is this:
```
package com.paypal.seif.crypto.impl;

import java.io.UnsupportedEncodingException;

import org.bouncycastle.jcajce.provider.digest.SHA3;

import com.paypal.seif.crypto.spi.Hash;

public class HashImpl implements Hash {

	private SHA3.Digest256 digest;
	public HashImpl() {
		this.digest = new SHA3.Digest256();
	}
	
	@Override
	public byte[] hash(String input) {
		this.digest.reset();
		byte[] inputBytes = null;
		try {
			inputBytes = input.getBytes("utf8");
		} catch (UnsupportedEncodingException e) {
			// This will never happen
		}
		byte[] output = new byte[256/8];
		output = this.digest.digest(inputBytes);
		return output;
	}
	
}
```

Here is my test:
```
package com.paypal.seif.crypto;

import static org.junit.Assert.*;

import java.util.Arrays;

import org.junit.Test;

import com.paypal.seif.crypto.spi.Factory;
import com.paypal.seif.crypto.spi.Hash;

public class HashTests {

	@Test
	public void testHash() {
		byte[] expected = new byte[] { 0x00 };
		Hash hash = Factory.getInstance().createHash();
		byte[] actual = hash.hash("abc");
		for(byte a: actual) {
			System.out.print(String.format("%02X", a));
		}
		System.out.println();
		assertTrue(Arrays.equals(actual, expected));
	}
	
}
```

The factory is a simple layer of abstraction:
```
package com.paypal.seif.crypto.spi;

import com.paypal.seif.crypto.impl.HashImpl;

public abstract class Factory {
	
	public abstract Hash createHash();
	
	public static Factory getInstance() {
		return new Implementation();
	}
	
	private static class Implementation extends Factory {

		@Override
		public Hash createHash() {
			return new HashImpl();
		}
		
	}
}
```

I am using version 1.55 of BC. Apache Ivy dependency:
```
<dependency org="org.bouncycastle" name="bcprov-jdk15on" rev="1.55"/>
```

**Comment by 4thex** [comment]
When I calculate the hash for "abc" using BC, I get this result:
3A985DA74FE225B2045C172D6BD390BD855F086E3E9D525B46BFE24511431532

It is not the same as the test here: [https://github.com/paypal/seifnode/blob/master/test/shatest.js]

I am not sure where the difference is. I can check in the code if you'd like.

The code I am using is this:
```
package com.paypal.seif.crypto.impl;

import java.io.UnsupportedEncodingException;

import org.bouncycastle.jcajce.provider.digest.SHA3;

import com.paypal.seif.crypto.spi.Hash;

public class HashImpl implements Hash {

	private SHA3.Digest256 digest;
	public HashImpl() {
		this.digest = new SHA3.Digest256();
	}
	
	@Override
	public byte[] hash(String input) {
		this.digest.reset();
		byte[] inputBytes = null;
		try {
			inputBytes = input.getBytes("utf8");
		} catch (UnsupportedEncodingException e) {
			// This will never happen
		}
		byte[] output = new byte[256/8];
		output = this.digest.digest(inputBytes);
		return output;
	}
	
}
```

Here is my test:
```
package com.paypal.seif.crypto;

import static org.junit.Assert.*;

import java.util.Arrays;

import org.junit.Test;

import com.paypal.seif.crypto.spi.Factory;
import com.paypal.seif.crypto.spi.Hash;

public class HashTests {

	@Test
	public void testHash() {
		byte[] expected = new byte[] { 0x00 };
		Hash hash = Factory.getInstance().createHash();
		byte[] actual = hash.hash("abc");
		for(byte a: actual) {
			System.out.print(String.format("%02X", a));
		}
		System.out.println();
		assertTrue(Arrays.equals(actual, expected));
	}
	
}
```

The factory is a simple layer of abstraction:
```
package com.paypal.seif.crypto.spi;

import com.paypal.seif.crypto.impl.HashImpl;

public abstract class Factory {
	
	public abstract Hash createHash();
	
	public static Factory getInstance() {
		return new Implementation();
	}
	
	private static class Implementation extends Factory {

		@Override
		public Hash createHash() {
			return new HashImpl();
		}
		
	}
}
```

I am using version 1.55 of BC. Apache Ivy dependency:
```
<dependency org="org.bouncycastle" name="bcprov-jdk15on" rev="1.55"/>
```

**Comment by 4thex** [comment]
I am going to close this issue and continue in dedicated repository.
