### ISSUE TITLE
Official mailing list or directions for contributing.

### ISSUE THREAD

**Issue by shofetim** [paypal/seifnode#28]
I understand that Seif is quite young, so there wouldn't yet be much activity or many contributors, but I for one am very interested, both in the alternative design of the system from a developer point of view, and the in the additional security properties it exhibits.

**Comment by harchu** [comment]
Hi @shofetim , Thank you for showing interest in Seif. We are in the process of creating a Slack channel and adding contribution guidelines. This should be ready soon.

**Comment by shofetim** [comment]
Just checking in. It looks like there hasn't been any commits in awhile, are things still moving along? Is there a way for more contributors to participate?

**Comment by douglascrockford** [comment]
We have been working on resource management and simplification of the Seif Protocol. There will be more news soon.

**Comment by aashish-sheshadri** [comment]
Added contributing guidelines.
