### ISSUE TITLE
Fails to install on Ubuntu 14

### ISSUE THREAD

**Issue by 4thex** [paypal/seifnode#29]
Please see the incomplete instructions here:
https://github.com/paypal/seifnode/wiki/Installing

When I try to install opencv with this command:

```brew install homebrew/science/opencv```

I get the following error
>...
==> python setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/home/ubuntu/.linuxbrew/Cellar/numpy/1.11.2 --single-version-externally-managed --record=installed.txt
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/numpy/02.python:
  File "/tmp/numpy-20161123-95404-1puah7u/numpy-1.11.2/numpy/distutils/command/build_src.py", line 147, in run
    self.build_sources()
  File "/tmp/numpy-20161123-95404-1puah7u/numpy-1.11.2/numpy/distutils/command/build_src.py", line 164, in build_sources
    self.build_extension_sources(ext)
  File "/tmp/numpy-20161123-95404-1puah7u/numpy-1.11.2/numpy/distutils/command/build_src.py", line 323, in build_extension_sources
    sources = self.generate_sources(sources, ext)
  File "/tmp/numpy-20161123-95404-1puah7u/numpy-1.11.2/numpy/distutils/command/build_src.py", line 376, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 407, in generate_config_h
    moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
  File "numpy/core/setup.py", line 40, in check_types
    out = check_types(*a, **kw)
  File "numpy/core/setup.py", line 269, in check_types
    "Cannot compile 'Python.h'. Perhaps you need to "
SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

I tried to install python-dev as the error suggests using the following command:

```sudo apt-get install python3.5-dev```

but that did not make a difference.

If I ignore this error and try to install anyway using command:

```npm install seifnode```

I get the following error:
> ...
> CMake Error at CMakeLists.txt:6 (find_package):
>  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
>  asked CMake to find a package configuration file provided by "OpenCV", but
>  CMake did not find one.
>
>  Could not find a package configuration file provided by "OpenCV" with any
>  of the following names:
>
>    OpenCVConfig.cmake
>    opencv-config.cmake
>
>  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
>  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
>  provides a separate development package or SDK, be sure it has been
>  installed.

I think this is simply a red herring telling me that opencv is not installed.

**Comment by aashish-sheshadri** [comment]
@4thex,

Were you able to install OpenCV finally? Brew is one choice but you can try other package managers to install OpenCV eg. Synaptic. npm install seifnode will not install the dependencies for you :)

**Comment by 4thex** [comment]
Thanks for checking. Still no luck. I am using the free Cloud9, so there is not enough disk space to build opencv. I havent't had a lot of time to invest in this, but I am trying different things. I am also contemplating stubbing out the opencv dependency so I can at least play with seifnode but not with the same level of security.

**Comment by aashish-sheshadri** [comment]
@4thex Seifnode does not require all the modules of OpenCV to be built -- if you look at seifrng (find_package (OpenCV REQUIRED core imgproc highgui)) we only need OpenCV core, imgproc and highgui. But if there is a simpler library that gets you to the camera and gets the same things done, do let us know!

**Comment by aashish-sheshadri** [comment]
Fixed with v1.0.3
