### ISSUE TITLE
Publish to npm? 

### ISSUE THREAD

**Issue by bcomnes** [paypal/seifnode#4]
Right now, `npm install seifnode` just 404s.

**Comment by mreinstein** [comment]
It might be intentional; I know when this project was first released it was billed as a way to solicit feedback from the general audience on the ideas presented here. Publishing it as a module might send the message that this is ready for consumption.

**Comment by bcomnes** [comment]
The readme should probrably reflect those intentions if thats the case.

**Comment by mreinstein** [comment]
good points. :+1:

**Comment by orcpac7** [comment]
NPM installation, 
npm install [path to git repo] 
fails on Windows 7 "Failed at the seifnode@0.0.0 preinstall script 'bash installrng.sh'."
Possibly because I was installing from an administrative command window rather than a bash shell.

**Comment by download13** [comment]
I'd strongly recommend publishing this module to npm. A lot of people aren't going to bother finding out the git url to install it, they just want to type `npm install seifnode` and be done.

**Comment by harchu** [comment]
Published to npm. Thanks!!
